name: Push
on:
  workflow_dispatch:
    inputs:
      value:
        required: true
        type: string
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo test
  two:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        broken: ${{ inputs.value }}
    steps:
      - name: Output
        run: echo ${{ matrix.broken }}
